POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Teppo",
    "number": "040-12345678"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Tomppa",
    "number": "04-1234567"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "To",
    "number": "040-12345678"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Teppo",
    "number": ""
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Teppo"
}